name: Lint
on:
  pull_request:
    types: [synchronize, edited, opened]
  push:
    branches: [main]
jobs:
  actions:
    runs-on: ubuntu-latest
    name: Review Dog - Lint GitHub Action Workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@v1
  json:
    runs-on: ubuntu-latest
    name: Lint JSON
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Run ESLint
        run: npx eslint
